create table player
(
    id         integer generated by default as identity,
    team_id    integer,
    first_name varchar(255),
    last_name  varchar(255),
    primary key (id)
);
create table team
(
    id        integer generated by default as identity,
    city      varchar(255),
    name varchar(255),
    primary key (id)
);
alter table if exists player add constraint FKdvd6ljes11r44igawmpm1mc5s foreign key (team_id) references team;