create table users
(
    id         integer generated by default as identity,
    first_name varchar(255),
    last_name  varchar(255),
    email      varchar(255),
    password   varchar(255),
    role varchar(5),
    primary key (id)
);